services:  
  app:    
    build:
      context: ./
      dockerfile: Dockerfile   
    ports:      
      - '8000:8000'    
    environment:      
      MONGO_URI: mongodb://mongo:27017/socialnet_express    
    depends_on:      
      - mongo    
    volumes:      
      - .:/build  
  mongo:    
    image: mongo:latest    
    volumes:      
      - mongo-data:/data/db    
    ports:      
      - '27015:27017'
volumes:  
  mongo-data: